In [120]:
import pandas as pd
import os
import numpy as np
import re
from datetime import datetime

In [121]:
list_df = []

# Read CSV

In [122]:
directory = 'GITHUB/detail_fix/'

for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    df = pd.read_csv(f) # membaca file CSV
    list_df.append(df)

In [123]:
directory2 = 'GITHUB/detail_fix2/'

for filename in os.listdir(directory2):
    f = os.path.join(directory2, filename)
    df = pd.read_csv(f) # membaca file CSV
    list_df.append(df)

In [124]:
list_df

[     Unnamed: 0            developer      id                metascore_how  \
 0             0            Aki Corp.  161964  Generally favorable reviews   
 1             1                 Opus  160856     Mixed or average reviews   
 2             2               Capcom  160749  Generally favorable reviews   
 3             3              Natsume  160922     Mixed or average reviews   
 4             4                Namco  101153  Generally favorable reviews   
 ..          ...                  ...     ...                          ...   
 519         519               Capcom  153407  Generally favorable reviews   
 520         520  NetherRealm Studios  200013  Generally favorable reviews   
 521         521  NetherRealm Studios  200014  Generally favorable reviews   
 522         522               Capcom  190523  Generally favorable reviews   
 523         523     Arc System Works  193562  Generally favorable reviews   
 
      metascore_review                                        

# Menggabungkan beberapa dataframe menjadi satu

In [178]:
# merge beberapa dataframe menjadi satu dataframe
df = pd.concat(list_df)

In [179]:
df.index = np.arange(0, len(df))

In [180]:
df = df.iloc[:, 1:]

In [181]:
df.head()

developer      id                metascore_how  metascore_review  \
0  Aki Corp.  161964  Generally favorable reviews              14.0   
1       Opus  160856     Mixed or average reviews               6.0   
2     Capcom  160749  Generally favorable reviews              17.0   
3    Natsume  160922     Mixed or average reviews               4.0   
4      Namco  101153  Generally favorable reviews              25.0   

                    multigenre player publisher  \
0  Action, Fighting, Wrestling    NaN       THQ   
1         Action, Fighting, 3D    NaN     Crave   
2         Action, Fighting, 2D    NaN    Capcom   
3         Action, Fighting, 2D    NaN    Bandai   
4         Action, Fighting, 3D    NaN     Namco   

                               publisher_url rating  \
0     https://www.metacritic.com/company/thq      T   
1   https://www.metacritic.com/company/crave      T   
2  https://www.metacritic.com/company/capcom      T   
3  https://www.metacritic.com/company/bandai      T   
4   https://www.metacritic.com/company/namco      T   

                 userscore_how  userscore_review  
0  Generally favorable reviews              97.0  
1     Mixed or average reviews              19.0  
2  Generally favorable reviews              32.0  
3     Mixed or average reviews              10.0  
4  Generally favorable reviews             181.0

In [182]:
cols = df.columns.tolist()
cols

['developer',
 'id',
 'metascore_how',
 'metascore_review',
 'multigenre',
 'player',
 'publisher',
 'publisher_url',
 'rating',
 'userscore_how',
 'userscore_review']

In [183]:
idx_cols = [1, 6, 7, 8, 0, 4, 5, 2, 3, 9, 10]

In [184]:
column = [cols[i] for i in idx_cols]
column

['id',
 'publisher',
 'publisher_url',
 'rating',
 'developer',
 'multigenre',
 'player',
 'metascore_how',
 'metascore_review',
 'userscore_how',
 'userscore_review']

In [185]:
df = df[column]

In [186]:
df

id                           publisher  \
0      161964                                 THQ   
1      160856                               Crave   
2      160749                              Capcom   
3      160922                              Bandai   
4      101153                               Namco   
...       ...                                 ...   
35767  529622                         D3Publisher   
35768  534152  Microsoft Game Studios, THQ Nordic   
35769  524955                  Bandai Namco Games   
35770  510717                           Rebellion   
35771  574158                   Xbox Game Studios   

                                           publisher_url rating  \
0                 https://www.metacritic.com/company/thq      T   
1               https://www.metacritic.com/company/crave      T   
2              https://www.metacritic.com/company/capcom      T   
3              https://www.metacritic.com/company/bandai      T   
4               https://www.metacritic.com/company/namco      T   
...                                                  ...    ...   
35767     https://www.metacritic.com/company/d3publisher      T   
35768  https://www.metacritic.com/company/microsoft-g...      M   
35769  https://www.metacritic.com/company/bandai-namc...      T   
35770       https://www.metacritic.com/company/rebellion      T   
35771  https://www.metacritic.com/company/xbox-game-s...    NaN   

                    developer                             multigenre  \
0                   Aki Corp.            Action, Fighting, Wrestling   
1                        Opus                   Action, Fighting, 3D   
2                      Capcom                   Action, Fighting, 2D   
3                     Natsume                   Action, Fighting, 2D   
4                       Namco                   Action, Fighting, 3D   
...                       ...                                    ...   
35767                 Sandlot  Action, Shooter, Third-Person, Arcade   
35768         Insomniac Games  Action, Shooter, Third-Person, Arcade   
35769  Digixart Entertainment   Adventure, General, 3D, Third-Person   
35770               Rebellion  Action, Shooter, Third-Person, Arcade   
35771           The Coalition  Action, Shooter, Third-Person, Arcade   

                                   player                metascore_how  \
0                                     NaN  Generally favorable reviews   
1                                     NaN     Mixed or average reviews   
2                                     NaN  Generally favorable reviews   
3                                     NaN     Mixed or average reviews   
4                                     NaN  Generally favorable reviews   
...                                   ...                          ...   
35767                     Up to 4 Players     Mixed or average reviews   
35768                     Up to 8 Players  Generally favorable reviews   
35769               No Online Multiplayer     Mixed or average reviews   
35770  Online Multiplayer Up to 4 Players     Mixed or average reviews   
35771                                 NaN  Generally favorable reviews   

       metascore_review                userscore_how  userscore_review  
0                  14.0  Generally favorable reviews              97.0  
1                   6.0     Mixed or average reviews              19.0  
2                  17.0  Generally favorable reviews              32.0  
3                   4.0     Mixed or average reviews              10.0  
4                  25.0  Generally favorable reviews             181.0  
...                 ...                          ...               ...  
35767              44.0  Generally favorable reviews              39.0  
35768               4.0  Generally favorable reviews             140.0  
35769              11.0     Mixed or average reviews              37.0  
35770              21.0     Mixed or average reviews              53.0  
35771       

# Check Datatype

In [187]:
df.dtypes

id                    int64
publisher            object
publisher_url        object
rating               object
developer            object
multigenre           object
player               object
metascore_how        object
metascore_review    float64
userscore_how        object
userscore_review    float64
dtype: object

# Bersihkan dataset

## a. Kolom 'is_online'

In [188]:
def clean_player(x):
    if x is np.nan:
        return 0
    else:
        return 1

In [189]:
df['is_online'] = df['player'].apply(clean_player)

In [190]:
df['is_online'] = df['is_online'].astype(object)

In [191]:
df['is_online'].unique()

array([0, 1], dtype=object)

In [192]:
df.head(3)

id publisher                              publisher_url rating  \
0  161964       THQ     https://www.metacritic.com/company/thq      T   
1  160856     Crave   https://www.metacritic.com/company/crave      T   
2  160749    Capcom  https://www.metacritic.com/company/capcom      T   

   developer                   multigenre player                metascore_how  \
0  Aki Corp.  Action, Fighting, Wrestling    NaN  Generally favorable reviews   
1       Opus         Action, Fighting, 3D    NaN     Mixed or average reviews   
2     Capcom         Action, Fighting, 2D    NaN  Generally favorable reviews   

   metascore_review                userscore_how  userscore_review is_online  
0              14.0  Generally favorable reviews              97.0         0  
1               6.0     Mixed or average reviews              19.0         0  
2              17.0  Generally favorable reviews              32.0         0

## b. Kolom 'metascore_review'

In [193]:
df['metascore_review'].unique() #before

array([ 14.,   6.,  17.,   4.,  25.,  20.,  15.,  24.,  19.,   7.,  23.,
        13.,  18.,  22.,  12.,  11.,  10.,   8.,  16.,  27.,   5.,  26.,
        45.,  39.,  41.,  30.,  21.,  33.,   9.,  32.,  31.,  28.,  36.,
        38.,  35.,  37.,  50.,  43.,  54.,  34.,  29.,  76.,  57.,  48.,
        62.,  44.,  46.,  53.,  47.,  59.,  52.,  61.,  51.,  58.,  68.,
        77.,  65.,  81.,  60.,  42.,  56.,  66.,  64.,  69.,  49.,  63.,
        70.,  55.,   0.,  40.,  71.,  72.,   3.,  78.,  74., 104.,  84.,
        92., 102.,  94., 126., 120.,  97., 108.,  83.,  91.,  67.,  75.,
        80.,  88.,  86.,  73.,  82.,  90.,  79.,  85.,  93.,  87.,  96.,
        89.,  99.,  95., 101., 106., 100., 113.,  98., 111., 122., 116.,
       115., 127., 124., 109., 134., 114., 110.,  nan, 107., 103., 119.,
       117., 121., 112.])

In [194]:
df['metascore_review'].fillna(0, inplace=True)

In [195]:
df['metascore_review'] = df['metascore_review'].astype('int')

In [196]:
df['metascore_review'].unique()

array([ 14,   6,  17,   4,  25,  20,  15,  24,  19,   7,  23,  13,  18,
        22,  12,  11,  10,   8,  16,  27,   5,  26,  45,  39,  41,  30,
        21,  33,   9,  32,  31,  28,  36,  38,  35,  37,  50,  43,  54,
        34,  29,  76,  57,  48,  62,  44,  46,  53,  47,  59,  52,  61,
        51,  58,  68,  77,  65,  81,  60,  42,  56,  66,  64,  69,  49,
        63,  70,  55,   0,  40,  71,  72,   3,  78,  74, 104,  84,  92,
       102,  94, 126, 120,  97, 108,  83,  91,  67,  75,  80,  88,  86,
        73,  82,  90,  79,  85,  93,  87,  96,  89,  99,  95, 101, 106,
       100, 113,  98, 111, 122, 116, 115, 127, 124, 109, 134, 114, 110,
       107, 103, 119, 117, 121, 112])

## c. Kolom 'userscore_review'

In [197]:
df['userscore_review'].unique() # before

array([  97.,   19.,   32., ..., 4560., 2078., 2100.])

In [143]:
df['userscore_review'].fillna(0, inplace=True)

In [144]:
df['userscore_review'] = df['userscore_review'].astype('int')

In [145]:
df['userscore_review'].unique()

array([  97,   19,   32, ..., 4560, 2078, 2100])

## d. Kolom 'id' 

In [146]:
df['id'] = df['id'].astype('object')

# Recheck Datatypes

In [152]:
df.dtypes

id                  object
publisher           object
publisher_url       object
rating              object
developer           object
multigenre          object
player              object
metascore_how       object
metascore_review     int32
userscore_how       object
userscore_review     int32
is_online           object
dtype: object

In [153]:
df.describe()

metascore_review  userscore_review
count      35772.000000      35772.000000
mean          17.420189        130.194174
std           16.569737        620.203675
min            0.000000          0.000000
25%            6.000000          6.000000
50%           11.000000         19.000000
75%           22.000000         63.000000
max          134.000000      33344.000000

# Check jika ada kolom yang null

In [45]:
df['rating'].isnull().values.any()

True

# Export CSV

In [154]:
df.to_csv('GITHUB/fix_merged/detail_game.csv')